### ISSUE TITLE
Assertion Error in `check_RobustNets_c10_accuracy`

### ISSUE THREAD

**Issue by tomginsberg** [sarafridov/RobustNets#1]
It looks like you may want to add a tolerance to the line below

```python
Traceback (most recent call last):
  File "RobustNets/RobustNets.py", line 136, in <module>
    iterate_over_RobustNets(
  File "RobustNets/RobustNets.py", line 48, in iterate_over_RobustNets
    function_applied_to_each_model(model_string)
  File "RobustNets/RobustNets.py", line 63, in check_RobustNets_c10_accuracy
    assert(test_acc == c10_acc), acc_string
AssertionError: c10_acc was 88.24, computed acc was 88.23
```

**Comment by bbartoldson** [comment]
Done. Thank you for the suggestion!
